[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "firstcommit"
version = "0.1.0"
description = "An open-source contributor onboarding simulator and repository readiness analysis tool."
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "requests>=2.31.0"
]

authors = [
    {name = "Martina Chiemezuo"}
]

[project.scripts]
firstcommit = "firstcommit.cli:main"

[tool.setuptools.packages.find]
where = ["src"]